// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeriodoAcademico.Data;

#nullable disable

namespace periodoAcademico.Migrations
{
    [DbContext(typeof(PeriodoContext))]
    [Migration("20240904025229_novasTabelas")]
    partial class novasTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PeriodoAcademico.Models.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Aprovado")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdTurma")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("MediaFinal")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("NotaProvaEspecial")
                        .HasColumnType("float");

                    b.Property<double?>("NotaProvaFinal")
                        .HasColumnType("float");

                    b.Property<Guid?>("TurmaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TurmaId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("PeriodoAcademico.Models.Prova", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<Guid?>("AlunoId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Avaliacao")
                        .HasColumnType("int");

                    b.Property<double>("Nota")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId1");

                    b.ToTable("Provas");
                });

            modelBuilder.Entity("PeriodoAcademico.Models.Turma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("PeriodoAcademico.Models.Aluno", b =>
                {
                    b.HasOne("PeriodoAcademico.Models.Turma", null)
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaId");
                });

            modelBuilder.Entity("PeriodoAcademico.Models.Prova", b =>
                {
                    b.HasOne("PeriodoAcademico.Models.Aluno", null)
                        .WithMany("Provas")
                        .HasForeignKey("AlunoId1");
                });

            modelBuilder.Entity("PeriodoAcademico.Models.Aluno", b =>
                {
                    b.Navigation("Provas");
                });

            modelBuilder.Entity("PeriodoAcademico.Models.Turma", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
